#!/bin/bash

# SPDX-FileCopyrightText: © 2019 Clifford Weinmann <https://www.cliffordweinmann.com/>
#
# SPDX-License-Identifier: MIT

# A quick helper for Make to get values from .env
source ./.env
echo ${!1}
