version = 1

[[annotations]]
path = ["*.md", ".version", ".env"]
precedence = "closest"
SPDX-FileCopyrightText = "© 2024 Clifford Weinmann <https://www.cliffordweinmann.com/>"
SPDX-License-Identifier = "MIT-0"
